/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.Pedido;
import classes.Produto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servicos.ServicoBancoCliente;
import servicos.ServicoBancoPedido;
import servicos.ServicoBancoProduto;
import servicos.ServicoPedido;

/**
 *
 * @author matheus.aviz
 */
public class FCadPedido extends javax.swing.JFrame {
 ServicoBancoCliente servicobancocliente = new ServicoBancoCliente();
 ServicoBancoProduto servicobancoproduto=new ServicoBancoProduto();
 ServicoBancoPedido servicobancopedido = new ServicoBancoPedido();
 ArrayList<ServicoPedido> lista_pedido = new ArrayList<>();
   
    public FCadPedido() {
        initComponents();
    }

    public void limparTela(){
        cbxProduto.setSelectedIndex(-1);
        txtQuantidade.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxCliente = new javax.swing.JComboBox<>();
        cbxProduto = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JTextField();
        jbCliente = new javax.swing.JLabel();
        jbProduto = new javax.swing.JLabel();
        jbQuantidade = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jAdicionarNovoProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cbxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteActionPerformed(evt);
            }
        });

        cbxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProdutoActionPerformed(evt);
            }
        });

        jbCliente.setText("Cliente ");

        jbProduto.setText("Produto");

        jbQuantidade.setText("Quantidade");

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jAdicionarNovoProduto.setText("Adicionar novo Produto");
        jAdicionarNovoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdicionarNovoProdutoMouseClicked(evt);
            }
        });
        jAdicionarNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdicionarNovoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbCliente)
                                .addComponent(jbProduto))
                            .addComponent(jbQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxProduto, javax.swing.GroupLayout.Alignment.TRAILING, 0, 314, Short.MAX_VALUE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jAdicionarNovoProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCliente))
                        .addGap(28, 28, 28)
                        .addComponent(cbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair)
                    .addComponent(jAdicionarNovoProduto))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed
       
    }//GEN-LAST:event_cbxClienteActionPerformed

    private void cbxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProdutoActionPerformed
        
    }//GEN-LAST:event_cbxProdutoActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        Cliente cliente = (Cliente) cbxCliente.getSelectedItem();
        Produto produto = (Produto) cbxProduto.getSelectedItem();


        if (txtQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade");
            txtQuantidade.requestFocus();
            return;
        }
        if(Integer.parseInt(txtQuantidade.getText()) > produto.getQuantidade()){
            JOptionPane.showMessageDialog(null, "Não é possivel comprar mais que a quantidade disponivel");
            txtQuantidade.requestFocus();
            return;
        }

        double valorProduto = produto.getPreco();
        valorProduto *= Double.parseDouble(txtQuantidade.getText());

        Pedido pedido = new Pedido(cliente.getCodigoCliente());
        ServicoPedido servicopedido = new ServicoPedido(pedido, Integer.parseInt(txtQuantidade.getText()), valorProduto, produto);
        lista_pedido.add(servicopedido);
        try {
            servicobancopedido.insert(lista_pedido);
            JOptionPane.showMessageDialog(null, "Pedido cadastrado com sucesso");
            txtQuantidade.setText("");
            cbxCliente.setSelectedIndex(-1);
            cbxCliente.setEnabled(true);
            cbxProduto.setSelectedIndex(-1);
            lista_pedido.clear();
            if (cbxProduto.getItemCount() == 1){
                jAdicionarNovoProduto.setVisible(false);
            } else{jAdicionarNovoProduto.setVisible(true);};
                
        } catch (SQLException ex) {
            Logger.getLogger(FCadPedido.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      atualizarListaCliente();
      atualizarListaProduto();
      cbxCliente.setSelectedIndex(-1);
      cbxProduto.setSelectedIndex(-1);
    if (cbxProduto.getItemCount() == 1){
        jAdicionarNovoProduto.setVisible(false);
    }
    }//GEN-LAST:event_formWindowActivated

    private void jAdicionarNovoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdicionarNovoProdutoMouseClicked
        Cliente cliente = (Cliente) cbxCliente.getSelectedItem();
        Produto produto = (Produto) cbxProduto.getSelectedItem();
        if (txtQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade");
            txtQuantidade.requestFocus();
            return;
        }
        if(Integer.parseInt(txtQuantidade.getText()) > produto.getQuantidade()){
            JOptionPane.showMessageDialog(null, "Não é possivel comprar mais que a quantidade disponivel");
            txtQuantidade.requestFocus();
            return;
        }
        double valorProduto = produto.getPreco();
        valorProduto *= Double.parseDouble(txtQuantidade.getText());
        cbxProduto.removeItemAt(cbxProduto.getSelectedIndex());
        if (cbxProduto.getItemCount() == 1){
            jAdicionarNovoProduto.setVisible(false);
        } 
        Pedido pedido = new Pedido(cliente.getCodigoCliente());
        ServicoPedido servicopedido = new ServicoPedido(pedido, Integer.parseInt(txtQuantidade.getText()), valorProduto, produto);
        lista_pedido.add(servicopedido);
        this.limparTela();
        cbxCliente.setEnabled(false);
    }//GEN-LAST:event_jAdicionarNovoProdutoMouseClicked

    private void jAdicionarNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarNovoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdicionarNovoProdutoActionPerformed

    
     private void atualizarListaProduto(){
        try{
        if(cbxProduto.getItemCount()>0){
            cbxProduto.removeAllItems();
        }
        ArrayList<Produto> lista = servicobancoproduto.getProdutoByLista();
        
        for (Produto a:lista){
            if (a.getQuantidade() > 0){
                cbxProduto.addItem(a);
            }
                
            }  
        
        }catch
        (SQLException ex) {
                Logger.getLogger(FCadPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
      private void atualizarListaCliente(){
        try {
            if (cbxCliente.getItemCount() > 0){
               cbxCliente.removeAllItems();
        }
        
            ArrayList<Cliente> lista = servicobancocliente.getClienteByLista();
        
         
          
            lista.forEach((u) -> {
                if("Ativo".equals(u.getSituacao())){
                    cbxCliente.addItem(u);
                }
            });      


            } catch (SQLException ex) {
                Logger.getLogger(FConsultCliente.class.getName()).log(Level.SEVERE, null, ex);
            }        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> cbxCliente;
    private javax.swing.JComboBox<Produto> cbxProduto;
    private javax.swing.JButton jAdicionarNovoProduto;
    private javax.swing.JLabel jbCliente;
    private javax.swing.JLabel jbProduto;
    private javax.swing.JLabel jbQuantidade;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
