/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import javax.swing.JMenuItem;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JMenu;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import java.awt.Font;

/**
 *
 * @author matheus.aviz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu1
     */
    public Menu() {
        initComponents();
    }
    public FCadCliente fcadcliente;
    public FCadProduto fcadproduto;
    public FCadPedido fcadpedido;
    public FConsultCliente fconsultcliente;
    public FConsultProduto fconsultproduto;
    public FConsultPedido fconsultpedido;
    public FRelatCliente frelatcliente;
    public FRelatProduto frelatproduto;
    public FRelatPedido frelatpedido;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCadClientes = new javax.swing.JMenuItem();
        jCadProdutos = new javax.swing.JMenuItem();
        jCadPedidos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jConsultClientes = new javax.swing.JMenuItem();
        jConsultProdutos = new javax.swing.JMenuItem();
        jConsultPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRelatClientes = new javax.swing.JMenuItem();
        jRelatProdutos = new javax.swing.JMenuItem();
        jRelatPedidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        jCadClientes.setText("Clientes");
        jCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jCadClientes);

        jCadProdutos.setText("Produtos");
        jCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jCadProdutos);

        jCadPedidos.setText("Pedidos");
        jCadPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadPedidosActionPerformed(evt);
            }
        });
        jMenu1.add(jCadPedidos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jConsultClientes.setText("Clientes");
        jConsultClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jConsultClientes);

        jConsultProdutos.setText("Produtos");
        jConsultProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jConsultProdutos);

        jConsultPedidos.setText("Pedidos");
        jConsultPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(jConsultPedidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatorios");

        jRelatClientes.setText("Clientes");
        jRelatClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jRelatClientes);

        jRelatProdutos.setText("Produtos");
        jRelatProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(jRelatProdutos);

        jRelatPedidos.setText("Pedidos");
        jRelatPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatPedidosActionPerformed(evt);
            }
        });
        jMenu3.add(jRelatPedidos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);
        
        jMenu4 = new JMenu("Sair");
        jMenu4.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				dispose();
			}
		});
        jMenuBar1.add(jMenu4);
        
        JLabel lblVendas = new JLabel("Vendas");
        lblVendas.setFont(new Font("Tahoma", Font.PLAIN, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(175)
        			.addComponent(lblVendas)
        			.addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(126)
        			.addComponent(lblVendas)
        			.addContainerGap(139, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadProdutosActionPerformed
        if (fcadproduto == null){
            fcadproduto = new FCadProduto();
        }
        fcadproduto.setVisible(true);
    }//GEN-LAST:event_jCadProdutosActionPerformed

    private void jRelatClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatClientesActionPerformed
        if ( frelatcliente == null){
            frelatcliente = new FRelatCliente();
        }
        frelatcliente.setVisible(true);
    }//GEN-LAST:event_jRelatClientesActionPerformed

    private void jRelatProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatProdutosActionPerformed
        if (frelatproduto == null){
            frelatproduto = new FRelatProduto();
        }
        frelatproduto.setVisible(true);
    }//GEN-LAST:event_jRelatProdutosActionPerformed

    private void jRelatPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatPedidosActionPerformed
        if (frelatpedido == null){
            frelatpedido = new FRelatPedido();
        }
        frelatpedido.setVisible(true);
    }//GEN-LAST:event_jRelatPedidosActionPerformed

    private void jConsultClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultClientesActionPerformed
        if (fconsultcliente == null){
            fconsultcliente = new FConsultCliente();
        }
        fconsultcliente.setVisible(true);
    }//GEN-LAST:event_jConsultClientesActionPerformed

    private void jConsultProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultProdutosActionPerformed
        if (fconsultproduto == null){
            fconsultproduto = new FConsultProduto();
        }
        fconsultproduto.setVisible(true);
    }//GEN-LAST:event_jConsultProdutosActionPerformed

    private void jConsultPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultPedidosActionPerformed
        if (fconsultpedido == null){
            fconsultpedido = new FConsultPedido();
        }
        fconsultpedido.setVisible(true);
    }//GEN-LAST:event_jConsultPedidosActionPerformed

    private void jCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadClientesActionPerformed
        if (fcadcliente == null){
            fcadcliente = new FCadCliente();
        }
        fcadcliente.setVisible(true);
    }//GEN-LAST:event_jCadClientesActionPerformed

    private void jCadPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadPedidosActionPerformed
        if (fcadpedido == null){
            fcadpedido = new FCadPedido();
        }
        fcadpedido.setVisible(true);
    }//GEN-LAST:event_jCadPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadClientes;
    private javax.swing.JMenuItem jCadPedidos;
    private javax.swing.JMenuItem jCadProdutos;
    private javax.swing.JMenuItem jConsultClientes;
    private javax.swing.JMenuItem jConsultPedidos;
    private javax.swing.JMenuItem jConsultProdutos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jRelatClientes;
    private javax.swing.JMenuItem jRelatPedidos;
    private javax.swing.JMenuItem jRelatProdutos;
    private JMenu jMenu4;
}
