/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;

/**
 *
 * @author matheus.aviz
 */
public class Menu extends javax.swing.JFrame {


    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public FCadCliente fcadcliente;
    public FCadProduto fcadproduto;
    public FCadPedido fcadpedido;
    public FConsultCliente fconsultcliente;
    public FConsultProduto fconsultproduto;
    public FConsultPedido fconsultpedido;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastros = new javax.swing.JMenu();
        jCadClientes = new javax.swing.JMenuItem();
        jCadProdutos = new javax.swing.JMenuItem();
        jCadPedidos = new javax.swing.JMenuItem();
        jConsultas = new javax.swing.JMenu();
        jConsultClientes = new javax.swing.JMenuItem();
        jConsultProdutos = new javax.swing.JMenuItem();
        jConsultPedidos = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenu();
        
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	jSairMouseClicked(evt);
            }

			private void jSairMouseClicked(MouseEvent evt) {
				dispose();				
			}
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCadastros.setText("Cadastros");
        jCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrosActionPerformed(evt);
            }
        });

        jCadClientes.setText("Clientes");
        jCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadClientesActionPerformed(evt);
            }
        });
        jCadastros.add(jCadClientes);

        jCadProdutos.setText("Produtos");
        jCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadProdutosActionPerformed(evt);
            }
        });
        jCadastros.add(jCadProdutos);

        jCadPedidos.setText("Pedidos");
        jCadPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadPedidosActionPerformed(evt);
            }
        });
        jCadastros.add(jCadPedidos);

        jMenuBar1.add(jCadastros);

        jConsultas.setText("Consultas");

        jConsultClientes.setText("Clientes");
        jConsultClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultClientesActionPerformed(evt);
            }
        });
        jConsultas.add(jConsultClientes);

        jConsultProdutos.setText("Produtos");
        jConsultProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultProdutosActionPerformed(evt);
            }
        });
        jConsultas.add(jConsultProdutos);

        jConsultPedidos.setText("Pedidos");
        jConsultPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultPedidosActionPerformed(evt);
            }
        });
        jConsultas.add(jConsultPedidos);

        jMenuBar1.add(jConsultas);

        jSair.setText("Sair");
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);
        
        JLabel lblEcommerce = new JLabel("Minha Loja");
        lblEcommerce.setFont(new Font("Tahoma", Font.PLAIN, 18));
        lblEcommerce.setAlignmentX(Component.CENTER_ALIGNMENT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(172)
        			.addComponent(lblEcommerce)
        			.addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(129)
        			.addComponent(lblEcommerce)
        			.addContainerGap(150, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadProdutosActionPerformed
        if (fcadproduto == null){
            fcadproduto = new FCadProduto();
        }
        fcadproduto.setVisible(true);
    }//GEN-LAST:event_jCadProdutosActionPerformed

    private void jCadPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadPedidosActionPerformed
        if (fcadpedido == null){
            fcadpedido = new FCadPedido();
        }
        fcadpedido.setVisible(true);
    }//GEN-LAST:event_jCadPedidosActionPerformed

    private void jCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrosActionPerformed

    }//GEN-LAST:event_jCadastrosActionPerformed

    private void jCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadClientesActionPerformed
        if (fcadcliente == null){
            fcadcliente = new FCadCliente();
        }
        fcadcliente.setVisible(true);
    }//GEN-LAST:event_jCadClientesActionPerformed

    private void jConsultClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultClientesActionPerformed
        if (fconsultcliente == null){
            fconsultcliente = new FConsultCliente();
        }
        fconsultcliente.setVisible(true);
    }//GEN-LAST:event_jConsultClientesActionPerformed

    private void jConsultProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultProdutosActionPerformed
        if (fconsultproduto == null){
            fconsultproduto = new FConsultProduto();
        }
        fconsultproduto.setVisible(true);
    }//GEN-LAST:event_jConsultProdutosActionPerformed

    private void jConsultPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultPedidosActionPerformed
        if (fconsultpedido == null){
            fconsultpedido = new FConsultPedido();
        }
        fconsultpedido.setVisible(true);    
    }//GEN-LAST:event_jConsultPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadClientes;
    private javax.swing.JMenuItem jCadPedidos;
    private javax.swing.JMenuItem jCadProdutos;
    private javax.swing.JMenu jCadastros;
    private javax.swing.JMenuItem jConsultClientes;
    private javax.swing.JMenuItem jConsultPedidos;
    private javax.swing.JMenuItem jConsultProdutos;
    private javax.swing.JMenu jConsultas;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jSair;
}
